numbers_=set({8,11,22,33,44,55,66,76,7,77,89,32,1,2,3,4,5})
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
print(numbers_)
numbers_.pop()
#print(numbers_)
#numbers_.pop()----->    numbers_.pop()
#                        KeyError: 'pop from an empty set'
numberss_=set({8,11,22,33,44,55,66,76,7,77,89,32,1,2,3,4,5})
numberss_.pop()
numberss_.pop()
numberss_.pop()
numberss_.pop()
print(numberss_)

# Records --------->
# 1 > {4, 5, 7, 8, 11, 76, 77, 22, 89, 32, 33, 44, 55}
